[build]
  publish = "dist"
  command = "pnpm run build"

[build.environment]
  NODE_VERSION = "20"
  PNPM_VERSION = "8.15.0"

[[redirects]]
  from = "/api/*"
  to = "https://maintenance-platform-backend.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_BASE_URL = "https://maintenance-platform-backend.onrender.com"
  VITE_SUPABASE_URL = "https://your-project.supabase.co"
  VITE_SUPABASE_ANON_KEY = "your-supabase-anon-key"

[context.deploy-preview.environment]
  VITE_API_BASE_URL = "https://maintenance-platform-backend.onrender.com"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://maintenance-platform-backend.onrender.com https://your-project.supabase.co;"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Admin-specific security headers
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

