name: maintenance_platform_mobile
description: "Maintenance Platform Mobile App for Egypt - Professional home services platform"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  provider: ^6.1.2
  riverpod: ^2.4.10
  flutter_riverpod: ^2.4.10

  # Navigation
  go_router: ^14.2.7

  # Network & API
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.4.0

  # Local Storage
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3

  # Authentication & Security
  firebase_core: ^2.31.1
  firebase_auth: ^4.19.6
  google_sign_in: ^6.2.1
  local_auth: ^2.2.0
  crypto: ^3.0.3

  # Location Services
  geolocator: ^12.0.0
  google_maps_flutter: ^2.6.1
  geocoding: ^3.0.0
  location: ^6.0.2

  # Notifications
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.2.2

  # UI Components & Design
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  lottie: ^3.1.2
  flutter_staggered_grid_view: ^0.7.0
  card_swiper: ^3.0.1
  smooth_page_indicator: ^1.2.0+3
  flutter_rating_bar: ^4.0.1

  # Internationalization
  intl: ^0.19.0
  easy_localization: ^3.0.7

  # Utilities
  permission_handler: ^11.3.1
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  file_picker: ^8.0.6
  share_plus: ^9.0.0
  package_info_plus: ^8.0.0
  device_info_plus: ^10.1.0
  connectivity_plus: ^6.0.3

  # Date & Time
  table_calendar: ^3.1.2

  # Forms & Validation
  flutter_form_builder: ^9.3.0
  form_builder_validators: ^10.0.1

  # Payment
  flutter_stripe: ^10.2.0

  # Chat & Communication
  socket_io_client: ^2.0.3+1
  emoji_picker_flutter: ^2.2.0

  # Camera & Media
  camera: ^0.11.0+2
  video_player: ^2.8.6
  image_cropper: ^7.1.0

  # Performance & Monitoring
  firebase_crashlytics: ^3.5.7
  firebase_analytics: ^10.10.7
  firebase_performance: ^0.9.4+7

  # Development
  logger: ^2.3.0
  equatable: ^2.0.5
  dartz: ^0.10.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # Code Generation
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.2
  hive_generator: ^2.0.1
  
  # Testing
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
    - assets/lottie/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
